[package]
name = "rjot"
version = "0.1.0"
authors = ["Brandon Greenwell <greenwell.brandon@gmail.com>"]
edition = "2021"
description = "A minimalist, command-line jotting utility that's fast, private, and git-friendly."
license = "MIT"
repository = "https://github.com/bgreenwell/rjot"
readme = "README.md"
keywords = ["cli", "journal", "notes", "markdown", "log"]
categories = ["command-line-utilities", "text-processing"]

[dependencies]
age = "0.10"
anyhow = "1.0"  # For cleaner error handling
chrono = "0.4"
clap = { version = "4.5", features = ["derive"] }
crossbeam-channel = "0.5"
dirs = "5.0.1" 
git2 = "0.18"
rand = "0.8"
rpassword = "7.3"
rustyline = "14.0"
rustyline-derive = "0.10.0" # NEW
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.9.34"
which = "4.4.2"
toml = "0.8"
uuid = { version = "1.8", features = ["v4", "serde"] }
zip = { version = "2.1", features = ["zstd"] }

# Non-Windows dependencies
[target.'cfg(not(windows))'.dependencies]
skim = "0.10.4"

[dev-dependencies]
assert_cmd = "2.0"
chrono = "0.4"
git2 = "0.18"
predicates = "3.1"
tempfile = "3.10"
